### ISSUE TITLE
Use UserInterface from zend-expressive-authentication

### ISSUE THREAD

**Issue by pdrosos** [zendframework/zend-expressive-authorization#12]
@weierophinney 
Could this be changed, so it uses the `Zend\Expressive\Authentication\UserInterface` instead?
https://github.com/zendframework/zend-expressive-authorization/blob/e06b440b6b60bceca480083fdb3572d7130789f6/src/AuthorizationMiddleware.php#L41
Would be great if it's with the changes from https://github.com/zendframework/zend-expressive-authentication/pull/4, so user can have multiple roles.

**Comment by weierophinney** [comment]
@pdrosos I think that was the plan from the beginning, but because we published this package first, we went with an interim solution.

@ezimuel, can you weigh in?

**Comment by ezimuel** [comment]
@pdrosos it's changed now with ver 0.2
