### ISSUE TITLE
Authorization based on username if not roles specified?

### ISSUE THREAD

**Issue by ezimuel** [zendframework/zend-expressive-authorization#14]
I'm thinking to extend the authorization middleware including this rule at [line 51](https://github.com/zendframework/zend-expressive-authorization/blob/master/src/AuthorizationMiddleware.php#L51):

```php
if (empty($user->getUserRoles())) {
    if ($this->authorization->isGranted($user->getUsername(), $request)) {
        return $handler->{HANDLER_METHOD}($request);
    }
}
```

If the authentication adapter doesn't return user's roles (like the `Basic Access Authentication` with `htpasswd` storage file), we can try to authorize based on the username. Thoughts?

**Comment by jguittard** [comment]
I think that this feature is a business matter. 
Having a user without any role within a business application might seem inconsistent. I’d leave this concern to fork/overridden implementation rather than inside the library.

**Comment by ezimuel** [comment]
I think @jguittard is right here. This sounds more like a specific business logic implementation. I'm closing this issue.
